apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: econ-graph
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-service:9090
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-service:3100
