apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: econ-graph
  labels:
    app: kube-state-metrics
spec:
  selector:
    app: kube-state-metrics
  ports:
  - name: http-metrics
    port: 8080
    targetPort: 8080
  - name: telemetry
    port: 8081
    targetPort: 8081
