apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: econ-graph
data:
  config.yml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://loki-service:3100/loki/api/v1/push
    scrape_configs:
    - job_name: static-logs
      static_configs:
      - targets:
        - localhost
        labels:
          job: static-logs
          __path__: /var/log/pods/econ-graph_econ-graph-backend-7ffbf56464-tbhz5_0f3216dc-25c6-4e59-bc83-009ee30d3bc9/backend/0.log
